# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
development:
  adapter: postgresql
  database: ddnext_development
  encoding: utf8
  username: dev
  password: hipass
  host: 127.0.0.1

test: &TEST
  adapter: postgresql
  database: ddnext_test
  encoding: utf8
  username: dev
  password: hipass
  host: 127.0.0.1

