development:
  defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false
  database: ddnext_development

test:
  defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 0
    pool_size: 1
    slave_ok: false
    ssl: false
  database: ddnext_test

# set these environment variables on your prod server
production:
  sessions:
    uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        skip_version_check: true
